//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::accounts::Entity as Accounts;
pub use super::locations::Entity as Locations;
pub use super::residents::Entity as Residents;
pub use super::residents::TimestampResident;
pub use super::residents::UpdateResident;
pub use super::timestamps::Entity as Timestamps;
pub use super::transaction_items::Entity as TransactionItems;
pub use super::transactions::Entity as Transactions;
pub use super::transactions::PostTransaction;
pub use super::users::Entity as Users;

pub trait OrmSerializable {}
impl OrmSerializable for TransactionItems {}
impl OrmSerializable for UpdateResident {}
impl OrmSerializable for Locations {}
impl OrmSerializable for Residents {}
impl OrmSerializable for Timestamps {}
impl OrmSerializable for TimestampResident {}
impl OrmSerializable for String {}
impl OrmSerializable for Accounts {}
impl OrmSerializable for Transactions {}
impl OrmSerializable for PostTransaction {}
impl OrmSerializable for Users {}
